name: release

on:
  push:

  repository_dispatch:
    types: [release]
    

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python main.py

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "package_py32_index.json,package_py32_cn_index.json"
          tag: "Nightly"
          allowUpdates: true
      
      - uses: git9527/setup-coscli@v2
        with:
          region: ${{ secrets.COS_REGION }}
          secret-id: ${{ secrets.COS_SECRET_ID }}
          secret-key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
          coscli-version: 'v0.12.0-beta' # Optional, default to 'v0.12.0-beta'.  Use 'latest' to get the latest version.
      - run: coscli sync ./temp cos://${{ secrets.COS_BUCKET }}/release --recursive --exclude "temp file path.txt"